-- CreateTable
CREATE TABLE "Auction" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "sourceUrl" TEXT,
    "title" TEXT NOT NULL,
    "category" TEXT NOT NULL DEFAULT 'autre',
    "auctionHouse" TEXT,
    "location" TEXT,
    "currentPrice" REAL NOT NULL,
    "buyerFeePct" REAL NOT NULL DEFAULT 0,
    "vatPct" REAL NOT NULL DEFAULT 0,
    "travelCost" REAL NOT NULL DEFAULT 0,
    "shippingCost" REAL NOT NULL DEFAULT 0,
    "condition" TEXT NOT NULL DEFAULT 'bon',
    "refurbHours" REAL NOT NULL DEFAULT 0,
    "comments" TEXT,
    "resaleFast" REAL NOT NULL DEFAULT 0,
    "resaleNormal" REAL NOT NULL DEFAULT 0,
    "resaleOptimized" REAL NOT NULL DEFAULT 0,
    "totalCost" REAL NOT NULL DEFAULT 0,
    "maxBudget" REAL NOT NULL DEFAULT 0,
    "potentialMargin" REAL NOT NULL DEFAULT 0,
    "netProfit" REAL NOT NULL DEFAULT 0,
    "roi" REAL NOT NULL DEFAULT 0,
    "score" INTEGER NOT NULL DEFAULT 0,
    "scoreBreakdown" TEXT NOT NULL DEFAULT '{}',
    "status" TEXT NOT NULL DEFAULT 'analysee',
    "finalPrice" REAL,
    "soldPrice" REAL,
    "soldAt" DATETIME,
    "itemId" TEXT,
    CONSTRAINT "Auction_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "Item" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Item" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "name" TEXT NOT NULL,
    "brand" TEXT,
    "category" TEXT NOT NULL DEFAULT 'autre',
    "priceNew" REAL,
    "priceUsed" REAL,
    "priceAvgObserved" REAL,
    "priceMin" REAL,
    "priceMax" REAL,
    "priceAuctionMax" REAL,
    "resaleFast" REAL,
    "resaleNormal" REAL,
    "resalePremium" REAL,
    "avgSaleTimeDays" REAL,
    "notes" TEXT,
    "usefulLinks" TEXT,
    "spareParts" TEXT,
    "checkPoints" TEXT
);
